# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-25 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_dice_prediction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dice',
            name='period',
            field=models.CharField(max_length=32, unique=True, verbose_name='周期'),
        ),
    ]
