# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-26 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_auto_20181025_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='dice',
            name='total',
            field=models.PositiveIntegerField(default=0, verbose_name='和值'),
        ),
    ]
