# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-06 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_dice_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dice',
            name='prediction',
        ),
        migrations.AddField(
            model_name='dice',
            name='eleven_prediction',
            field=models.CharField(default='', max_length=16, verbose_name='十一期预测'),
        ),
        migrations.AddField(
            model_name='dice',
            name='five_prediction',
            field=models.CharField(default='', max_length=16, verbose_name='五期预测'),
        ),
        migrations.AddField(
            model_name='dice',
            name='nine_prediction',
            field=models.CharField(default='', max_length=16, verbose_name='九期预测'),
        ),
        migrations.AddField(
            model_name='dice',
            name='seven_prediction',
            field=models.CharField(default='', max_length=16, verbose_name='七期预测'),
        ),
        migrations.AddField(
            model_name='dice',
            name='three_prediction',
            field=models.CharField(default='', max_length=16, verbose_name='三期预期'),
        ),
    ]
