# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-15 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0006_dice_custom_prediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='dice',
            name='custom_balance',
            field=models.PositiveIntegerField(default=0, verbose_name='自定义余额'),
        ),
        migrations.AddField(
            model_name='dice',
            name='eleven_balance',
            field=models.PositiveIntegerField(default=0, verbose_name='十一期余额'),
        ),
        migrations.AddField(
            model_name='dice',
            name='five_balance',
            field=models.PositiveIntegerField(default=0, verbose_name='五期余额'),
        ),
        migrations.AddField(
            model_name='dice',
            name='nine_balance',
            field=models.PositiveIntegerField(default=0, verbose_name='九期余额'),
        ),
        migrations.AddField(
            model_name='dice',
            name='seven_balance',
            field=models.PositiveIntegerField(default=0, verbose_name='七期余额'),
        ),
        migrations.AddField(
            model_name='dice',
            name='three_balance',
            field=models.PositiveIntegerField(default=0, verbose_name='三期余额'),
        ),
        migrations.AlterField(
            model_name='dice',
            name='custom_prediction',
            field=models.CharField(default='', max_length=16, verbose_name='自定义预测'),
        ),
    ]
