# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-15 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0007_auto_20181115_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dice',
            name='custom_balance',
            field=models.IntegerField(default=0, verbose_name='自定义余额'),
        ),
        migrations.AlterField(
            model_name='dice',
            name='eleven_balance',
            field=models.IntegerField(default=0, verbose_name='十一期余额'),
        ),
        migrations.AlterField(
            model_name='dice',
            name='five_balance',
            field=models.IntegerField(default=0, verbose_name='五期余额'),
        ),
        migrations.AlterField(
            model_name='dice',
            name='nine_balance',
            field=models.IntegerField(default=0, verbose_name='九期余额'),
        ),
        migrations.AlterField(
            model_name='dice',
            name='seven_balance',
            field=models.IntegerField(default=0, verbose_name='七期余额'),
        ),
        migrations.AlterField(
            model_name='dice',
            name='three_balance',
            field=models.IntegerField(default=0, verbose_name='三期余额'),
        ),
    ]
