# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-15 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0009_auto_20181115_1001'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientIp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=64, verbose_name='客户端ip')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
            ],
            options={
                'db_table': 'tb_client_ip',
            },
        ),
    ]
