# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-15 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0010_clientip'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientip',
            name='url',
            field=models.CharField(default='', max_length=255, verbose_name='访问链接'),
        ),
    ]
